config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :patients, only: [:new, :create, :edit, :update]
  resources :standard_surveys, only: [:edit, :update, :show] do
    member do
      resources :actions, only: [:new, :create]
    end
  end

  namespace :twilio do
    resources :sms_statuses, only: [:create]
  end
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController

  before_action :authenticate_admin_user!

  def new
    @form = CreateActionForm.new(standard_survey: standard_survey)
  end

  def create
    @form = CreateActionForm.new(standard_survey_params)

    if @form.submit
      redirect_to admin_standard_survey_path(standard_survey), notice: 'Action effectuée'
    else
      render :new
    end
  end


  private

    def standard_survey
      @_standard_survey = StandardSurvey.find(params[:id])
    end


    def standard_survey_params
      params.require(:create_action_form)
            .permit(:action_comment)
            .merge(standard_survey: standard_survey)
    end

end

app/views/actions/new.html.erb
<%= render layout: '/shared/forms_outside_active_admin', locals: {back_button_path: admin_standard_survey_path(@form.standard_survey), title: "Effectuer une action"} do %>
  <%= simple_form_for(@form, method: :post, url: actions_path(id: @form.standard_survey.id)) do |f| %>
    <%= f.input :action_comment, label: "Commentaire", autofocus: true, as: :text %>

    <%= f.button :submit, value: "Action effectuée", data: { disable_with: "Validation en cours ..." }, class: "btn btn-primary" %>
  <% end %>
<% end %>