config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :patients, only: [:new, :create, :edit, :update]
  resources :standard_surveys, only: [:edit, :update, :show] do
    member do
      resources :actions, only: [:new, :create]
    end
  end

  namespace :twilio do
    resources :sms_statuses, only: [:create]
  end
end

app/models/patient.rb
class Patient < ApplicationRecord
  validates_presence_of :first_name, :last_name, :cellphone_number, :otp_secret

  phony_normalize :cellphone_number, default_country_code: 'FR'
  phony_normalize :relative_cellphone_number, default_country_code: 'FR'

  has_many :standard_surveys, dependent: :destroy
  belongs_to :command_center, optional: true

  enum gender: {male: 'male', female: 'female'}, _prefix: true
  enum covid_initial_symptom: {mild: 'mild', post_severe: 'post_severe', post_critical: 'post_critical'}, _prefix: true
  enum comorbidity_smoking: {yes: 'yes', never: 'never', former_smoker: 'former_smoker'}, _prefix: true

  scope :green,                              -> { where(latest_standard_survey_status: ::StandardSurvey::STATUS_GREEN)}
  scope :yellow,                             -> { where(latest_standard_survey_status: ::StandardSurvey::STATUS_YELLOW)}
  scope :orange,                             -> { where(latest_standard_survey_status: ::StandardSurvey::STATUS_ORANGE)}
  scope :red,                                -> { where(latest_standard_survey_status: ::StandardSurvey::STATUS_RED)}
  scope :without_completed_standard_survey,  -> { where(latest_standard_survey_status: nil)}
  scope :active,                             -> { where(active: true)}

  def to_s
    return "Patient ##{id}" if first_name.blank? && last_name.blank?

    "#{first_name} #{last_name}"
  end

  def display_name
    to_s
  end

  def otp_service
    @_otp_service ||= ROTP::TOTP.new(otp_secret, issuer: 'Authentication service')
  end

  def generate_otp
    otp_service.now
  end

  def verify_otp(code_to_check)
    otp_service.verify(code_to_check || '', drift_behind: 1.day.to_i)
  end

  def needs_a_new_standard_survey?
    return true unless last_standard_survey

    last_standard_survey.created_at < survey_periodicity_in_hours.hours.ago
  end

  def last_standard_survey
    @_last_standard_survey ||= standard_surveys.order(created_at: :desc).take
  end

  def comorbibity?
    [
      comorbidity_chronic_cardiac_disease?,
      comorbidity_chronic_pulmonary_disease?,
      comorbidity_asthma?,
      comorbidity_chronic_kidney_disease?,
      comorbidity_liver_disease?,
      comorbidity_mild_liver_disease?,
      comorbidity_chronic_neurological_disorder?,
      comorbidity_malignant_neoplasia?,
      comorbidity_chronic_hemathological_disease?,
      comorbidity_hiv?,
      comorbidity_obesity?,
      comorbidity_diabetes_with_complications?,
      comorbidity_diabetes?,
      comorbidity_rheumatologic_disease?,
      comorbidity_dementia?,
      comorbidity_malnutrition?,
      comorbidity_smoking == "yes",
      comorbidity_other?,
    ].any?
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  before_action :authenticate_admin_user!

  def new
    @form = CreatePatientForm.new(pregnant_since_in_weeks: 0)
  end

  def create
    @form = CreatePatientForm.new(patient_create_params)

    if @form.submit
      redirect_to admin_patient_path(@form.patient), notice: 'Patient créé.'
    else
      render :new
    end
  end

  def edit
    @form = UpdatePatientForm.new(patient: patient)
    @form.assign_attributes_from_patient
  end

  def update
    @form = UpdatePatientForm.new(patient_update_params)

    if @form.submit
      redirect_to admin_patient_path(@form.patient), notice: 'Patient mis à jour.'
    else
      render :edit
    end
  end

  private

    def patient
      @_patient ||= Patient.find(params[:id])
    end


    def patient_create_params
      params.require(:create_patient_form).permit(patient_attributes)
    end

    def patient_update_params
      params.require(:update_patient_form).permit(patient_attributes).merge(patient: patient)
    end

    def patient_attributes
      [:first_name, :last_name, :cellphone_number, :address, :email, :relative_cellphone_number, :general_practitioner, :covid_general_practitioner, :gender, :birthdate, :is_healthcare_professional, :pregnant, :home_caregivers, :home_caregivers_type, :covid_initial_symptom, :covid_initial_symptoms_diagnosed_on, :covid_initial_symptoms_started_on, :covid_treatment_started_on, :interstitial_alveolus_infiltrates, :notable_long_term_treatments, :sars_cov_2_treatment, :sars_cov_2_treatment_name, :home_follow_up_elligible, :comorbidity_chronic_cardiac_disease, :comorbidity_chronic_pulmonary_disease, :comorbidity_asthma, :comorbidity_chronic_kidney_disease, :comorbidity_liver_disease, :comorbidity_mild_liver_disease, :comorbidity_chronic_neurological_disorder, :comorbidity_malignant_neoplasia, :comorbidity_chronic_hemathological_disease, :comorbidity_hiv, :comorbidity_obesity, :comorbidity_diabetes_with_complications, :comorbidity_diabetes, :comorbidity_rheumatologic_disease, :comorbidity_dementia, :comorbidity_malnutrition, :comorbidity_smoking, :comorbidity_other, :comorbidity_other_comment, :pregnant_since_in_weeks, :command_center_id]
    end


end

app/views/patients/_form_attributes.html.erb
<%= f.input :command_center_id, autofocus: true, collection: CommandCenter.all.order(name: :asc), include_blank: false %>
<%= f.input :covid_general_practitioner, as: :text %>

<fieldset class="form-group">
  <legend><%= t('simple_form.fieldsets.patient_form.contact_informations') %></legend>

  <%= f.input :last_name %>
  <%= f.input :first_name %>
  <%= f.input :address, as: :text %>
  <%= f.input :cellphone_number %>
  <%= f.input :email %>
  <%= f.input :relative_cellphone_number %>
  <%= f.input :general_practitioner, as: :text %>
  <hr/>
</fieldset>

<fieldset class="form-group">
  <legend><%= t('simple_form.fieldsets.patient_form.patient_informations') %></legend>

  <%= f.input :gender, as: :select, collection: Patient.enum_filter_collection(:genders) %>
  <%= f.input :birthdate, input_html: {data: {controller: "flatpickr"}} %>
  <%= f.input :is_healthcare_professional, as: :select %>
  <%= f.input :pregnant, as: :select %>
  <%= f.input :pregnant_since_in_weeks, as: :integer %>
  <%= f.input :notable_long_term_treatments, as: :text %>
  <hr/>
</fieldset>

<fieldset class="form-group">
  <legend><%= t('simple_form.fieldsets.patient_form.comorbidities') %></legend>

  <div class="row">
    <div class="col-sm">
      <%= f.input :comorbidity_chronic_cardiac_disease, as: :radio_buttons %>
      <%= f.input :comorbidity_chronic_pulmonary_disease, as: :radio_buttons %>
      <%= f.input :comorbidity_asthma, as: :radio_buttons %>
      <%= f.input :comorbidity_chronic_kidney_disease, as: :radio_buttons %>
      <%= f.input :comorbidity_liver_disease, as: :radio_buttons %>
      <%= f.input :comorbidity_mild_liver_disease, as: :radio_buttons %>
      <%= f.input :comorbidity_chronic_neurological_disorder, as: :radio_buttons %>
      <%= f.input :comorbidity_malignant_neoplasia, as: :radio_buttons %>
      <%= f.input :comorbidity_chronic_hemathological_disease, as: :radio_buttons %>
      <%= f.input :comorbidity_hiv, as: :radio_buttons %>
    </div>
    <div class="col-sm">
      <%= f.input :comorbidity_obesity, as: :radio_buttons %>
      <%= f.input :comorbidity_diabetes_with_complications, as: :radio_buttons %>
      <%= f.input :comorbidity_diabetes, as: :radio_buttons %>
      <%= f.input :comorbidity_rheumatologic_disease, as: :radio_buttons %>
      <%= f.input :comorbidity_dementia, as: :radio_buttons %>
      <%= f.input :comorbidity_malnutrition, as: :radio_buttons %>
      <%= f.input :comorbidity_smoking, as: :radio_buttons, collection: Patient.enum_filter_collection(:comorbidity_smokings) %>
      <%= f.input :comorbidity_other, as: :radio_buttons %>
      <%= f.input :comorbidity_other_comment, as: :text %>
    </div>
  </div>
  <hr/>
</fieldset>

<fieldset class="form-group">
  <legend><%= t('simple_form.fieldsets.patient_form.covid_informations') %></legend>
  <%= f.input :covid_initial_symptom, as: :select, collection: Patient.enum_filter_collection(:covid_initial_symptoms) %>
  <%= f.input :covid_initial_symptoms_started_on, input_html: {data: {controller: "flatpickr"}} %>
  <%= f.input :covid_initial_symptoms_diagnosed_on, input_html: {data: {controller: "flatpickr"}} %>
  <%= f.input :interstitial_alveolus_infiltrates, as: :select %>
  <%= f.input :sars_cov_2_treatment, as: :select %>
  <%= f.input :sars_cov_2_treatment_name, as: :text %>
  <%= f.input :covid_treatment_started_on, input_html: {data: {controller: "flatpickr"}} %>
  <%= f.input :home_caregivers, as: :select %>
  <%= f.input :home_caregivers_type %>
  <hr/>
</fieldset>

<%= t('simple_form.messages.patient_form.home_follow_up_elligible_criterias_html') %>

<%= f.input :home_follow_up_elligible, as: :select %>

app/views/patients/edit.html.erb
<%= render layout: '/shared/forms_outside_active_admin', locals: {back_button_path: admin_patients_path, title: t('simple_form.titles.update_patient_form')} do %>
  <%= simple_form_for(@form, method: :put, url: patient_path(@form.patient)) do |f| %>

    <%= render 'form_attributes', f: f %>

    <%= f.button :submit, value: t('simple_form.actions.update_patient_form.submit'), data: { disable_with: t('simple_form.actions.update_patient_form.disable_with') }, class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/patients/new.html.erb
<%= render layout: '/shared/forms_outside_active_admin', locals: {back_button_path: admin_patients_path, title: t('simple_form.titles.create_patient_form')} do %>
  <%= simple_form_for(@form, method: :post, url: patients_path) do |f| %>

    <%= render 'form_attributes', f: f %>

    <%= f.button :submit, value: t('simple_form.actions.create_patient_form.submit'), data: { disable_with: t('simple_form.actions.create_patient_form.disable_with') }, class: "btn btn-primary" %>
  <% end %>
<% end %>