config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :patients, only: [:new, :create, :edit, :update]
  resources :standard_surveys, only: [:edit, :update, :show] do
    member do
      resources :actions, only: [:new, :create]
    end
  end

  namespace :twilio do
    resources :sms_statuses, only: [:create]
  end
end

app/models/standard_survey.rb
class StandardSurvey < ApplicationRecord

  self.ignored_columns = ['breathing_difficulty']

  include Tokenable
  has_token :public
  after_create :set_public_token

  include UrlHelper

  belongs_to :patient

  STATUS_GREEN = 'green'.freeze
  STATUS_YELLOW = 'yellow'.freeze
  STATUS_ORANGE = 'orange'.freeze
  STATUS_RED = 'red'.freeze

  enum breathing_difficulty_borg_scale: {"0" => 0, "0,5" => 0.5, "1" => 1, "2" => 2, "3" => 3, "4" => 4, "5" => 5, "6" => 6, "7" => 7, "8" => 8, "9" => 9, "10" => 10}, _prefix: true
  enum status: {green: STATUS_GREEN, yellow: STATUS_YELLOW, orange: STATUS_ORANGE, red: STATUS_RED}

  scope :completed,                               -> { where.not(completed_at: nil)}
  scope :to_complete,                             -> { where(completed_at: nil)}
  scope :action_not_done_yet,                     -> { where(action_done_at: nil)}
  scope :action_done,                             -> { where.not(action_done_at: nil)}
  scope :action_needed,                           -> { where(action_needed: true).action_not_done_yet}
  scope :action_needed_due_to_lack_of_response,   -> { to_complete.where("created_at < ?", 6.hours.ago).action_not_done_yet}


  def to_s
    "Réponse - #{patient} - ##{id}"
  end

  def temporary_url
    url_helper.edit_standard_survey_url(id: public_token, otp: patient.generate_otp)
  end

  def set_status!
    StandardSurvey::SetStatus.call(self)
  end

  def previous_completed_standard_survey
    @_previous_completed_standard_survey ||= patient.standard_surveys.completed.where("id < ?", id).order(completed_at: :desc).take
  end

  def action_not_done_yet?
    action_done_at.nil?
  end

  def action_needed?
    return true if super

    completed_at.nil? && created_at < 6.hours.ago
  end



end

app/controllers/standard_surveys_controller.rb
class StandardSurveysController < ApplicationController

  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def edit
    @form = UpdateStandardSurveyForm.new(standard_survey: standard_survey, otp: params[:otp])
  end

  def update
    @form = UpdateStandardSurveyForm.new(standard_survey_params)
    @form.standard_survey = standard_survey

    if @form.submit
      render :update
    else
      render :edit
    end
  end

  def not_found
    render :not_found
  end

  private

    def standard_survey
      @_standard_survey = StandardSurvey.to_complete.find_by!(public_token: params[:id])
    end


    def standard_survey_params
      params.require(:update_standard_survey_form).permit(:body_temperature, :cohabitants_recent_change, :breathing_difficulty_borg_scale, :heartbeats_per_minute, :recent_chest_pain, :agreed_containment, :agreed_containment_comment, :respiratory_rate_in_cycles_per_minute, :recent_cold_chill, :otp)
    end

end

app/views/standard_surveys/_update_green.html.erb
<div class="alert alert-success" role="alert">
  Merci pour vos réponses.<br/>
  Les données que vous avez renseignées sont rassurantes. Vous recevrez un nouveau questionnaire dans 24h.<br/>
  <strong>En cas de problème, contactez le +33 7 57 91 69 11.</strong>
</div>

app/views/standard_surveys/_update_orange.html.erb
<div class="alert alert-success" role="alert">
  Merci pour vos réponses.<br/>
  Vos données sont en cours d'analyse par l'équipe médicale qui prendra contact rapidement avec vous.<br/>
  <strong>En cas de problème urgent, contactez le +33 7 57 91 69 11.</strong>
</div>

app/views/standard_surveys/_update_red.html.erb
<div class="alert alert-success" role="alert">
  Merci pour vos réponses.<br/>
  Vos données sont en cours d'analyse par l'équipe médicale qui prendra contact rapidement avec vous.<br/>
  <strong>En cas de problème urgent, contactez le +33 7 57 91 69 11.</strong>
</div>

app/views/standard_surveys/_update_yellow.html.erb
<div class="alert alert-success" role="alert">
  Merci pour vos réponses.<br/>
  Les symptômes que vous avez décrits ne sont pas inquiétants, mais justifient néanmoins une surveillance un peu plus rapprochée. Vous recevrez un nouveau questionnaire dans 12h.<br/>
  <strong>En cas de problème, contactez le +33 7 57 91 69 11.</strong>
</div>

app/views/standard_surveys/edit.html.erb
<%= render layout: '/shared/public_forms_outside_active_admin', locals: {title: t('simple_form.titles.update_standard_survey_form')} do %>

  <div class="alert alert-info" role="alert">
    <%= t('simple_form.messages.update_standard_survey_form.intro_html') %>
  </div>

  <hr/>

  <%= simple_form_for(@form, method: :patch, url: standard_survey_path(id: @form.standard_survey.public_token)) do |f| %>
    <%= f.input :otp, as: :hidden %>

    <%= f.input :cohabitants_recent_change, autofocus: true, as: :radio_buttons %>
    <%= f.input :body_temperature, as: :float %>

    <%= t('simple_form.messages.update_standard_survey_form.body_temperature_instructions_html') %>

    <%= f.input :breathing_difficulty_borg_scale, as: :select, include_blank: false, collection: StandardSurvey.enum_filter_collection(:breathing_difficulty_borg_scales) %>
    <%= f.input :heartbeats_per_minute, as: :integer %>

    <%= t('simple_form.messages.update_standard_survey_form.heartbeats_per_minute_instructions_html') %>

    <%= f.input :respiratory_rate_in_cycles_per_minute, as: :integer %>
    <%= f.input :recent_cold_chill, as: :radio_buttons %>
    <%= f.input :recent_chest_pain, as: :radio_buttons %>
    <%= f.input :agreed_containment, as: :radio_buttons %>
    <%= f.input :agreed_containment_comment, as: :text %>

    <%= f.button :submit, value: t('simple_form.actions.update_standard_survey_form.submit'), data: { disable_with: t('simple_form.actions.update_standard_survey_form.disable_with') }, class: "btn btn-primary" %>
  <% end %>
<% end %>

app/views/standard_surveys/not_found.fr.html.erb
<%= render layout: '/shared/public_forms_outside_active_admin', locals: {title: t('simple_form.titles.update_standard_survey_form')} do %>
  <div class="alert alert-warning" role="alert">
    Ce questionnaire n'existe pas ou a déjà été rempli.<br/>
    <strong>En cas de problème urgent, contactez le +33 7 57 91 69 11.</strong>
  </div>
<% end %>

app/views/standard_surveys/not_found.html.erb
<%= render layout: '/shared/public_forms_outside_active_admin', locals: {title: "Questionnaire de suivi à domicile - Coronavirus Covid 19"} do %>
  <div class="alert alert-warning" role="alert">
    Ce questionnaire n'existe pas ou a déjà été rempli.<br/>
    <strong>En cas de problème urgent, contactez le +33 7 57 91 69 11.</strong>
  </div>
<% end %>

app/views/standard_surveys/update.html.erb
<%= render layout: '/shared/public_forms_outside_active_admin', locals: {title: t('simple_form.titles.update_standard_survey_form')} do %>
  <%= render partial: "update_#{@form.standard_survey.status}" %>
<% end %>